name: Generate Changelog

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-cliff
        run: |
          # 下载最新版本的 git-cliff
          CLIFF_VERSION="2.7.0"
          curl -sSL "https://github.com/orhun/git-cliff/releases/download/v${CLIFF_VERSION}/git-cliff-${CLIFF_VERSION}-x86_64-unknown-linux-gnu.tar.gz" | tar -xz
          sudo mv git-cliff-*/git-cliff /usr/local/bin/
          chmod +x /usr/local/bin/git-cliff
          git-cliff --version

      - name: Generate changelog
        run: |
          git-cliff --config cliff.toml --verbose -o CHANGELOG.md

      - name: Commit changelog
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
          if [ -f "CHANGELOG.md" ]; then
            git add CHANGELOG.md
            if git diff --quiet && git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "docs: 更新 CHANGELOG [skip ci]"
              git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
            fi
          fi

