name: Generate Changelog

on:
  push:
    branches:
      - main
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit changelog
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
          if [ -f "CHANGELOG.md" ]; then
            git add CHANGELOG.md
            git diff --quiet && git diff --staged --quiet || git commit -m "docs: 更新 CHANGELOG"
            git push
          fi

